"""CLI command implementations."""

import os
import sys
from pathlib import Path
from typing import Optional
import requests


def get_sdk_path() -> str:
    """Get the SDK installation path."""
    import agentscope
    return str(Path(agentscope.__file__).parent.parent)


def setup_cmd(args):
    """Setup AgentScope monitoring."""
    workspace = Path(args.workspace).expanduser().resolve()
    
    if not workspace.exists():
        print(f"❌ Workspace does not exist: {workspace}")
        sys.exit(1)
    
    print(f"🔧 Setting up AgentScope for {args.framework}")
    print(f"   Workspace: {workspace}")
    if args.name:
        print(f"   Instance:  {args.name}")
    print(f"   Backend:   {args.backend}")
    print()
    
    if args.framework == "nanobot":
        setup_nanobot(workspace, args.name, args.backend, args.force)
    else:
        print(f"❌ Framework '{args.framework}' setup not yet implemented")
        sys.exit(1)
    
    print()
    print("✅ Setup complete!")
    print()
    print("Next steps:")
    print("  1. Ensure AgentScope backend is running:")
    print("     cd /path/to/agentscope/backend && python main.py")
    print("  2. Restart your nanobot instance")
    print("  3. Send a test message and check http://localhost:3000")


def setup_nanobot(workspace: Path, name: Optional[str], backend_url: str, force: bool):
    """Setup nanobot with AgentScope monitoring."""
    # Check for existing configuration
    sitecustomize_path = workspace / "sitecustomize.py"
    
    if sitecustomize_path.exists() and not force:
        print(f"⚠️  sitecustomize.py already exists: {sitecustomize_path}")
        print("   Use --force to overwrite")
        sys.exit(1)
    
    # Create sitecustomize.py
    sdk_path = get_sdk_path()
    sitecustomize_content = f'''"""Auto-load AgentScope instrumentation for nanobot.
Generated by agentscope setup
"""
import sys
import os

# Add AgentScope SDK to path
agentscope_path = "{sdk_path}"
if agentscope_path not in sys.path:
    sys.path.insert(0, agentscope_path)

# Set backend URL
os.environ["AGENTSCOPE_BACKEND_URL"] = "{backend_url}"
os.environ["AGENTSCOPE_AUTO_INSTRUMENT"] = "true"

try:
    from agentscope.instrumentation.nanobot_instrumentor import instrument
    instrument()
    print("✅ AgentScope: Instrumentation loaded", file=sys.stderr)
except Exception as e:
    print(f"⚠️ AgentScope: Failed to load instrumentation: {{e}}", file=sys.stderr)
'''
    
    sitecustomize_path.write_text(sitecustomize_content)
    print(f"✅ Created: {sitecustomize_path}")
    
    # Create setup instructions for plist
    plist_instructions = f"""
# LaunchAgent Configuration for {name or 'nanobot'}

Add to your plist file:

<key>WorkingDirectory</key>
<string>{workspace}</string>

<key>EnvironmentVariables</key>
<dict>
    <key>PYTHONPATH</key>
    <string>{sdk_path}</string>
    <key>AGENTSCOPE_BACKEND_URL</key>
    <string>{backend_url}</string>
</dict>

Or use the sitecustomize.py approach (already created above).
"""
    
    instructions_path = workspace / "AGENTSCOPE_SETUP.md"
    instructions_path.write_text(plist_instructions)
    print(f"✅ Created: {instructions_path}")
    
    # Check if nanobot is installed in workspace venv
    venv_python = workspace.parent / ".venv" / "bin" / "python3"
    if not venv_python.exists():
        venv_python = workspace.parent / "venv" / "bin" / "python3"
    
    if venv_python.exists():
        print(f"✅ Found Python: {venv_python}")
        # Check if agentscope is installed
        result = os.system(f"{venv_python} -c 'import agentscope' 2>/dev/null")
        if result != 0:
            print()
            print("⚠️  AgentScope SDK not found in venv")
            print(f"   Install with: {venv_python} -m pip install agentscope-monitor")


def status_cmd(args):
    """Check AgentScope status."""
    print("🔍 Checking AgentScope status...")
    print()
    
    # Check backend
    try:
        response = requests.get(f"{args.backend}/api/health", timeout=5)
        if response.status_code == 200:
            data = response.json()
            print(f"✅ Backend:     {args.backend} (online)")
            print(f"   Version:     {data.get('version', 'unknown')}")
        else:
            print(f"⚠️  Backend:     {args.backend} (HTTP {response.status_code})")
    except requests.exceptions.ConnectionError:
        print(f"❌ Backend:     {args.backend} (offline)")
    except Exception as e:
        print(f"⚠️  Backend:     {args.backend} ({e})")
    
    print()
    
    # Check SDK
    try:
        import agentscope
        print(f"✅ SDK:         installed ({agentscope.__file__})")
    except ImportError:
        print("❌ SDK:         not installed")
        print("   Install with: pip install agentscope-monitor")
    
    print()
    
    # Check nanobot instrumentation
    try:
        from agentscope.instrumentation.nanobot_instrumentor import _instrumented
        if _instrumented:
            print("✅ Nanobot:     instrumented")
        else:
            print("⚠️  Nanobot:     not instrumented (restart required)")
    except ImportError:
        print("⚠️  Nanobot:     instrumentation not available")


def uninstall_cmd(args):
    """Remove AgentScope monitoring."""
    workspace = Path(args.workspace).expanduser().resolve()
    
    if not workspace.exists():
        print(f"❌ Workspace does not exist: {workspace}")
        sys.exit(1)
    
    print(f"🗑️  Removing AgentScope from {args.framework}")
    print(f"   Workspace: {workspace}")
    print()
    
    # Remove sitecustomize.py
    sitecustomize_path = workspace / "sitecustomize.py"
    if sitecustomize_path.exists():
        sitecustomize_path.unlink()
        print(f"✅ Removed: {sitecustomize_path}")
    
    # Remove instructions
    instructions_path = workspace / "AGENTSCOPE_SETUP.md"
    if instructions_path.exists():
        instructions_path.unlink()
        print(f"✅ Removed: {instructions_path}")
    
    print()
    print("✅ Uninstall complete!")
    print()
    print("Note: Restart your nanobot instance to complete removal")
